apiVersion: v1
kind: Service
metadata:
  name: e-com-shop-service
  labels:
    app: e-com-shop
spec:
  selector:
    app: e-com-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP